# Generated by Django 4.2.16 on 2024-09-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.JSONField()),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('company', models.JSONField()),
            ],
        ),
    ]
